/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as AdminOrdersManagementRouteImport } from './routes/admin/orders-management'
import { Route as AdminDesignsManagementRouteImport } from './routes/admin/designs-management'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCampaignsManagementRouteImport } from './routes/admin/campaigns-management'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDesignsRouteImport } from './routes/_authenticated/designs'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders/$orderId'
import { Route as AuthenticatedOrdersOrderIdSuccessRouteImport } from './routes/_authenticated/orders/$orderId.success'

const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersManagementRoute = AdminOrdersManagementRouteImport.update({
  id: '/orders-management',
  path: '/orders-management',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDesignsManagementRoute = AdminDesignsManagementRouteImport.update({
  id: '/designs-management',
  path: '/designs-management',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCampaignsManagementRoute =
  AdminCampaignsManagementRouteImport.update({
    id: '/campaigns-management',
    path: '/campaigns-management',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignsRoute = AuthenticatedDesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdSuccessRoute =
  AuthenticatedOrdersOrderIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedOrdersOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/browse': typeof BrowseRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/designs': typeof AuthenticatedDesignsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/campaigns-management': typeof AdminCampaignsManagementRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/designs-management': typeof AdminDesignsManagementRoute
  '/admin/orders-management': typeof AdminOrdersManagementRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRouteWithChildren
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/orders/$orderId/success': typeof AuthenticatedOrdersOrderIdSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/browse': typeof BrowseRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/designs': typeof AuthenticatedDesignsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/campaigns-management': typeof AdminCampaignsManagementRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/designs-management': typeof AdminDesignsManagementRoute
  '/admin/orders-management': typeof AdminOrdersManagementRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRouteWithChildren
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/orders/$orderId/success': typeof AuthenticatedOrdersOrderIdSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/browse': typeof BrowseRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/designs': typeof AuthenticatedDesignsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/campaigns-management': typeof AdminCampaignsManagementRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/designs-management': typeof AdminDesignsManagementRoute
  '/admin/orders-management': typeof AdminOrdersManagementRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRouteWithChildren
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/orders/$orderId/success': typeof AuthenticatedOrdersOrderIdSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/register'
    | '/cart'
    | '/checkout'
    | '/designs'
    | '/profile'
    | '/admin/campaigns-management'
    | '/admin/dashboard'
    | '/admin/designs-management'
    | '/admin/orders-management'
    | '/campaigns/$campaignId'
    | '/orders/$orderId'
    | '/orders/'
    | '/orders/$orderId/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/register'
    | '/cart'
    | '/checkout'
    | '/designs'
    | '/profile'
    | '/admin/campaigns-management'
    | '/admin/dashboard'
    | '/admin/designs-management'
    | '/admin/orders-management'
    | '/campaigns/$campaignId'
    | '/orders/$orderId'
    | '/orders'
    | '/orders/$orderId/success'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/browse'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/designs'
    | '/_authenticated/profile'
    | '/admin/campaigns-management'
    | '/admin/dashboard'
    | '/admin/designs-management'
    | '/admin/orders-management'
    | '/campaigns/$campaignId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/orders/'
    | '/_authenticated/orders/$orderId/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders-management': {
      id: '/admin/orders-management'
      path: '/orders-management'
      fullPath: '/admin/orders-management'
      preLoaderRoute: typeof AdminOrdersManagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/designs-management': {
      id: '/admin/designs-management'
      path: '/designs-management'
      fullPath: '/admin/designs-management'
      preLoaderRoute: typeof AdminDesignsManagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/campaigns-management': {
      id: '/admin/campaigns-management'
      path: '/campaigns-management'
      fullPath: '/admin/campaigns-management'
      preLoaderRoute: typeof AdminCampaignsManagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/designs': {
      id: '/_authenticated/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof AuthenticatedDesignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId/success': {
      id: '/_authenticated/orders/$orderId/success'
      path: '/success'
      fullPath: '/orders/$orderId/success'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdSuccessRouteImport
      parentRoute: typeof AuthenticatedOrdersOrderIdRoute
    }
  }
}

interface AuthenticatedOrdersOrderIdRouteChildren {
  AuthenticatedOrdersOrderIdSuccessRoute: typeof AuthenticatedOrdersOrderIdSuccessRoute
}

const AuthenticatedOrdersOrderIdRouteChildren: AuthenticatedOrdersOrderIdRouteChildren =
  {
    AuthenticatedOrdersOrderIdSuccessRoute:
      AuthenticatedOrdersOrderIdSuccessRoute,
  }

const AuthenticatedOrdersOrderIdRouteWithChildren =
  AuthenticatedOrdersOrderIdRoute._addFileChildren(
    AuthenticatedOrdersOrderIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDesignsRoute: typeof AuthenticatedDesignsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRouteWithChildren
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDesignsRoute: AuthenticatedDesignsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRouteWithChildren,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCampaignsManagementRoute: typeof AdminCampaignsManagementRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDesignsManagementRoute: typeof AdminDesignsManagementRoute
  AdminOrdersManagementRoute: typeof AdminOrdersManagementRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCampaignsManagementRoute: AdminCampaignsManagementRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDesignsManagementRoute: AdminDesignsManagementRoute,
  AdminOrdersManagementRoute: AdminOrdersManagementRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BrowseRoute: BrowseRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
